### ISSUE TITLE
inappropriate error message

### ISSUE THREAD

**Issue by syohex** [konoha-project/libzen#51]
I suppose that error message should be like `"a" is undefined` in such case.

```
%  java -jar libzen.jar

LibZen0.1 (Reference Implementation of D-Script) on Java JVM-1.7.0_51
Copyright (c) 2013-2014, Konoha project authors
Accept: zen-0.1 zen-trycatch-0.1 
Produce: 0.1
>>> function f(){return (int)a;}
((stdin):1) [error] unsafe downcast: var => int
    function f(){return (int)a;}
                         ^

---

function f(): int {
   return perror("((stdin):1) [error] unsafe downcast: var => int\n\tfunction f(){return (int)a;}\n\t                     ^");
}
```

**Comment by kkuramitsu** [comment]
this is fixed. thank you.

On Thu, Mar 13, 2014 at 5:51 PM, Syohei YOSHIDA notifications@github.comwrote:

> I suppose that error message should be like "a" is undefined in such case.
> 
> %  java -jar libzen.jar
> 
> LibZen0.1 (Reference Implementation of D-Script) on Java JVM-1.7.0_51
> Copyright (c) 2013-2014, Konoha project authors
> Accept: zen-0.1 zen-trycatch-0.1
> Produce: 0.1
> 
> > > > function f(){return (int)a;}
> > > > ((stdin):1) [error] unsafe downcast: var => int
> > > >     function f(){return (int)a;}
> > > > 
> > > > ##                          ^
> 
> function f(): int {
>    return perror("((stdin):1) [error] unsafe downcast: var => int\n\tfunction f(){return (int)a;}\n\t                     ^");
> }
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/konoha-project/libzen/issues/51
> .

## 

Kimio Kuramitsu, Ph.D. Associate Professor
kimio@ynu.ac.jp    http://www.ubicg.ynu.ac.jp/
Konoha Project Leader. http://konoha.sourceforge.jp/
TEL +81-45-339-4139(4128) FAX: +81-45-338-1157
